/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIncomeRouteImport } from './routes/onboarding.income'
import { Route as OnboardingExpensesRouteImport } from './routes/onboarding.expenses'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIncomeRoute = OnboardingIncomeRouteImport.update({
  id: '/onboarding/income',
  path: '/onboarding/income',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingExpensesRoute = OnboardingExpensesRouteImport.update({
  id: '/onboarding/expenses',
  path: '/onboarding/expenses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/welcome': typeof WelcomeRoute
  '/onboarding/expenses': typeof OnboardingExpensesRoute
  '/onboarding/income': typeof OnboardingIncomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/welcome': typeof WelcomeRoute
  '/onboarding/expenses': typeof OnboardingExpensesRoute
  '/onboarding/income': typeof OnboardingIncomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/welcome': typeof WelcomeRoute
  '/onboarding/expenses': typeof OnboardingExpensesRoute
  '/onboarding/income': typeof OnboardingIncomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/welcome'
    | '/onboarding/expenses'
    | '/onboarding/income'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/welcome' | '/onboarding/expenses' | '/onboarding/income'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/welcome'
    | '/onboarding/expenses'
    | '/onboarding/income'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  WelcomeRoute: typeof WelcomeRoute
  OnboardingExpensesRoute: typeof OnboardingExpensesRoute
  OnboardingIncomeRoute: typeof OnboardingIncomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/income': {
      id: '/onboarding/income'
      path: '/onboarding/income'
      fullPath: '/onboarding/income'
      preLoaderRoute: typeof OnboardingIncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/expenses': {
      id: '/onboarding/expenses'
      path: '/onboarding/expenses'
      fullPath: '/onboarding/expenses'
      preLoaderRoute: typeof OnboardingExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  WelcomeRoute: WelcomeRoute,
  OnboardingExpensesRoute: OnboardingExpensesRoute,
  OnboardingIncomeRoute: OnboardingIncomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
